# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Message.proto
# Protobuf Python Version: 5.29.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc1',
    'Message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMessage.proto\"&\n\tHandshake\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\"7\n\x06Object\x12\x0e\n\x06sender\x18\x01 \x01(\x03\x12\x10\n\x08receiver\x18\x02 \x01(\x03\x12\x0b\n\x03msg\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKE']._serialized_start=17
  _globals['_HANDSHAKE']._serialized_end=55
  _globals['_OBJECT']._serialized_start=57
  _globals['_OBJECT']._serialized_end=112
# @@protoc_insertion_point(module_scope)
